# Generated by Django 4.0.2 on 2022-02-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_hospital_id', models.CharField(max_length=255, null=True, verbose_name='from_hospital_id')),
                ('target_hospital_id', models.CharField(max_length=255, null=True, verbose_name='target_hospital_id')),
                ('created_time', models.DateTimeField(null=True, verbose_name='created_time')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='status')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='type')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['from_hospital_id'], name='hospital_from'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_hospital_id'], name='hospital_target'),
        ),
    ]
